#TODO
  backend:
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - MODEL=${MODEL}
      - METRICS_ENDPOINT=${METRICS_ENDPOINT}
      - METRICS_TOKEN=${METRICS_TOKEN}
      - METRICS_ENGINE=${METRICS_ENGINE}
      - METRICS_SAMPLE=${METRICS_SAMPLE}
    depends_on:
      - llama
    networks:
      - ai_network
      - web_network